### ISSUE TITLE
Newer Version of Python in Templates

### ISSUE THREAD

**Issue by KKamaa** [sunflowerit/waftlib#24]
@Hussam-Suleiman @thomaspaulb could we upgrade the version of python in waftlib templates from **3.6.15** to at least >= **3.7**

**Comment by KKamaa** [comment]
oh ok cool, some functionalities keep being updated in newer versions not to forget about bug fixes just like any software.So maybe not now, but we could take advantage of new functionalities and also be secure from bugs you can check which is the most [stable version](https://www.python.org/downloads/) currently. Anyway it was just a thought, cause I had an issue with debugger that was sorted by upgrading the python version.

**Comment by thomaspaulb** [comment]
Some things to keep in mind:

- If we use a version of Python eg 3.8, it's best to use the latest version of it, so in this case Python 3.8.16. Nothing will break if you change 3.8.x to 3.8.y, they are always backward compatible
- If we choose a Python version we should always use a version that Odoo and OCA use to test with. Odoo usually chooses the versions that Ubuntu LTS versions packages, and OCA uses what Odoo uses. Eg for [14.0 they use 3.6](https://github.com/OCA/web/blob/14.0/.github/workflows/test.yml#L38) and for [15.0 they use 3.8](https://github.com/OCA/web/blob/15.0/.github/workflows/test.yml#L38)
- If we use a different Python version for a project, all the Python packages in `requirements.txt` should change as well, so it's not so easy to do

I think we shouldn't bother to change the Python version for Waft below 14.0. For 14.0 maybe we can go to 3.8, but we should test it properly first. For 15.0 we can use Python 3.8, and for 16.0 we can use [Python 3.10](https://github.com/OCA/web/blob/16.0/.github/workflows/test.yml#L38)

@KKamaa If you want to change a Python version for a project, you can just do so yourself, by changing `.python-version` and modifying `requirements.txt`, and then deleting `.pyenv` and `.venv` and re-running `./bootstrap` and `./build`. If you can get it to work, you can test it out on test server, and then we can adjust it in production as well if it works, and THEN we can apply it in waft templates maybe.

**Comment by Hussam-Suleiman** [comment]
@thomaspaulb 
years ago we had Doodba on ubuntu 18.04, and we used the default ubuntu python version for Odoo from version 11.0 to version 14.0, now we have a fully isolated virtual python version environment, so, if python version 3.8.16 working fine for Odoo version 14.0 we can apply it by default, just we need to be sure that we don't have incompatible codes in our Odoo 14.0 codes, so, yes we can apply it for Therp helpdesk and Freshfilter test instances and then if it works well we can apply it by default to the productions.
